// Archived comments from the WordPress blog (2004-2020), keyed by permalink.
//
// The per-post `comments.json` files are generated by tools/wp-comments and
// committed; nothing here reads the WordPress export. This module only shapes
// them for templates: it drops pingbacks, builds the reply tree, and keys
// everything by permalink so a post layout can do `comments[page.url]`.
//
// Pingbacks are kept in the JSON on disk but not surfaced here -- almost every
// blog that sent one is long gone. To start rendering them, stop filtering on
// `kind` below; no regeneration is needed.

import fs from "node:fs";
import path from "node:path";

const BLOG_DIR = "content/blog";

/** Build a nested reply tree from a flat, chronologically ordered list. */
function buildTree(comments) {
	const byId = new Map(comments.map((c) => [c.id, { ...c, children: [] }]));
	const roots = [];

	for (const c of byId.values()) {
		// A reply whose parent is not present -- because the parent was a
		// pingback, or was removed as spam -- is promoted to top level rather
		// than dropped. Losing a comment to tidy the tree would be worse than
		// showing it unattached.
		const parent = c.parent != null ? byId.get(c.parent) : undefined;
		if (parent) {
			parent.children.push(c);
		} else {
			roots.push(c);
		}
	}
	return roots;
}

export default function () {
	const index = {};
	if (!fs.existsSync(BLOG_DIR)) {
		return index;
	}

	for (const dir of fs.readdirSync(BLOG_DIR).sort()) {
		const file = path.join(BLOG_DIR, dir, "comments.json");
		if (!fs.existsSync(file)) {
			continue;
		}

		const doc = JSON.parse(fs.readFileSync(file, "utf8"));
		const visible = doc.comments.filter((c) => c.kind === "comment");
		if (visible.length === 0) {
			continue;
		}

		index[doc.post] = {
			count: visible.length,
			// Pingbacks are excluded above but counted here so the template can
			// mention them if it ever wants to.
			pingbackCount: doc.comments.length - visible.length,
			tree: buildTree(visible),
		};
	}

	return index;
}
